[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = true

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
anyhow = "=1.0.63"
base64 = "=0.13.0"
cargo-registry-index = { path = "cargo-registry-index" }
cargo-registry-markdown = { path = "cargo-registry-markdown" }
cargo-registry-s3 = { path = "cargo-registry-s3" }
chrono = { version = "=0.4.22", features = ["serde"] }
clap = { version = "=3.2.19", features = ["derive", "unicode"] }

conduit = "=0.10.0"
conduit-conditional-get = "=0.10.0"
conduit-cookie = "=0.10.0"
conduit-git-http-backend = "=0.10.0"
conduit-hyper = "=0.4.1"
conduit-middleware = "=0.10.0"
conduit-router = "=0.10.0"
conduit-static = "=0.10.0"

cookie = { version = "=0.16.0", features = ["secure"] }
dashmap = { version = "=5.4.0", features = ["raw-api"] }
derive_deref = "=1.1.1"
dialoguer = "=0.10.2"
diesel = { version = "=2.0.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "=2.0.0"
diesel_migrations = { version = "=2.0.0", features = ["postgres"] }
dotenv = "=0.15.0"
flate2 = "=1.0.24"
futures-channel = { version = "=0.3.24", default-features = false }
futures-util = "=0.3.24"
hashbrown = { version = "=0.12.3", default-features = false }
hex = "=0.4.3"
http = "=0.2.8"
hyper = { version = "=0.14.20", features = ["client", "http1"] }
indexmap = { version = "=1.9.1", features = ["serde-1"] }
indicatif = "=0.17.0"
ipnetwork = "=0.20.0"
tikv-jemallocator = { version = "=0.5.0", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "=0.10.1", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
minijinja = "=0.18.1"
moka = "=0.9.3"
oauth2 = { version = "=4.2.3", default-features = false, features = ["reqwest"] }
parking_lot = "=0.12.1"
prometheus = { version = "=0.13.1", default-features = false }
rand = "=0.8.5"
reqwest = { version = "=0.11.11", features = ["blocking", "gzip", "json"] }
scheduled-thread-pool = "=0.2.6"
semver = { version = "=1.0.13", features = ["serde"] }
sentry = { version = "=0.27.0", features = ["tracing"] }
sentry-conduit = { version = "=0.7.0", default-features = false }
serde = { version = "=1.0.144", features = ["derive"] }
serde_json = "=1.0.85"
sha2 = "=0.10.3"
spdx = "=0.9.0"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "e87cf37" }
tar = "=0.4.38"
tempfile = "=3.3.0"
thiserror = "=1.0.33"
tokio = { version = "=1.20.1", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "=0.5.9"
tracing = "=0.1.36"
tracing-subscriber = { version = "=0.3.15", features = ["env-filter"] }
url = "=2.2.2"

[dev-dependencies]
cargo-registry-index = { path = "cargo-registry-index", features = ["testing"] }
claims = "=0.6.0"
conduit-test = "=0.10.0"
hyper-tls = "=0.5.0"
insta = { version = "=1.19.1", features = ["redactions", "yaml"] }
once_cell = "=1.13.1"
tokio = "=1.20.1"
tower-service = "=0.3.2"

[build-dependencies]
diesel = { version = "=2.0.0", features = ["postgres"] }
diesel_migrations = { version = "=2.0.0", features = ["postgres"] }
dotenv = "=0.15.0"
